// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyyCXehypOC4NbnvcGnTHEVxJQ-MxZOsI',
    appId: '1:356580977014:web:c5e9e57a2a8c10efaaf257',
    messagingSenderId: '356580977014',
    projectId: 'planetas-astros-firebd',
    authDomain: 'planetas-astros-firebd.firebaseapp.com',
    storageBucket: 'planetas-astros-firebd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1KkV0BcLR4op1KfhvUcqrOKRDEjum29M',
    appId: '1:356580977014:android:435e40a0d15f0382aaf257',
    messagingSenderId: '356580977014',
    projectId: 'planetas-astros-firebd',
    storageBucket: 'planetas-astros-firebd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGqKGyrIMnWiJkEekinEvj8tloOUCJMDU',
    appId: '1:356580977014:ios:5f6bdbec3bfd30ddaaf257',
    messagingSenderId: '356580977014',
    projectId: 'planetas-astros-firebd',
    storageBucket: 'planetas-astros-firebd.firebasestorage.app',
    iosBundleId: 'com.example.planetasAstros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGqKGyrIMnWiJkEekinEvj8tloOUCJMDU',
    appId: '1:356580977014:ios:5f6bdbec3bfd30ddaaf257',
    messagingSenderId: '356580977014',
    projectId: 'planetas-astros-firebd',
    storageBucket: 'planetas-astros-firebd.firebasestorage.app',
    iosBundleId: 'com.example.planetasAstros',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyyCXehypOC4NbnvcGnTHEVxJQ-MxZOsI',
    appId: '1:356580977014:web:5a61faa72d580b80aaf257',
    messagingSenderId: '356580977014',
    projectId: 'planetas-astros-firebd',
    authDomain: 'planetas-astros-firebd.firebaseapp.com',
    storageBucket: 'planetas-astros-firebd.firebasestorage.app',
  );
}
